#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     motorDrive1,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorDrive2,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorDrive3,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorDrive4,   tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// The Doppler Effect
// FTC #5703 subteam A

// Autonomous Program

task main()
{
}
